//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/DeadEchoProject/Scripts/InputSystem/InputMaps.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaps: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaps()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaps"",
    ""maps"": [
        {
            ""name"": ""PC_Map"",
            ""id"": ""4b03f44b-7a1f-46c6-b0c7-c4ba244796cc"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""098a3513-4350-4f8b-8630-88edd0cb5a54"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d2b5adfe-c34e-460c-89d4-3deb83e3787e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SprintAction"",
                    ""type"": ""Button"",
                    ""id"": ""20232a6b-56b0-409b-9325-82cea4458247"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReloadAction"",
                    ""type"": ""Button"",
                    ""id"": ""05b057e4-ddbe-4c7e-b513-7afaff3dfac5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootAction"",
                    ""type"": ""Button"",
                    ""id"": ""0ce985b0-ff59-4651-8348-475c8f227ccb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimAction"",
                    ""type"": ""Button"",
                    ""id"": ""74ed7541-5876-4bcc-8bfe-24deadeff1a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpAction"",
                    ""type"": ""Button"",
                    ""id"": ""86b93aa6-8a7c-4c23-aa91-6a96ee6fbff3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CrouchAction"",
                    ""type"": ""Button"",
                    ""id"": ""8ba6f3c5-b014-4ec2-a48b-3743121d18eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeGunMode"",
                    ""type"": ""Button"",
                    ""id"": ""62d6a029-ca79-490d-b5a9-9cfaed9680ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryGun"",
                    ""type"": ""Button"",
                    ""id"": ""bf3ba2e1-5351-421a-8f39-4a7894e0105d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryGun"",
                    ""type"": ""Button"",
                    ""id"": ""e2787042-9cf5-4ad1-870d-00826d51bac7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7ecfc215-37ba-4710-b7ec-8040a8f747ae"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""123cc452-67c2-4d4a-901d-8272598d5e49"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5406688a-4511-4fb3-a749-9566977b36c5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2fae29b4-f5b7-43d7-a183-521d8e937978"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""67b95f10-7f03-444e-b322-aa34b10acfae"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5f65f4a1-ca67-4833-b2f9-2d4cb63ffd27"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""551dcbf2-16d1-4b6b-a58e-3416bada146a"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SprintAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0c0bf4d-8c6d-4783-8c12-c288995b740a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""915a71ff-630d-4414-b47f-71b45d5ffeae"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a6ed2fc-749b-4453-b113-72814d065177"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fb44032-9168-4008-be58-44dea3ee670f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""610f58d6-e4fe-426e-9297-f6dd7311c5fc"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrouchAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1cc373f-2eb8-4b61-a613-8005ab0c6b94"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeGunMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80bfcb6d-a9a7-44de-afc8-6c678e32c34e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3159b0d3-2639-4326-9bd8-214f682b220e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PC_Map
        m_PC_Map = asset.FindActionMap("PC_Map", throwIfNotFound: true);
        m_PC_Map_Look = m_PC_Map.FindAction("Look", throwIfNotFound: true);
        m_PC_Map_Move = m_PC_Map.FindAction("Move", throwIfNotFound: true);
        m_PC_Map_SprintAction = m_PC_Map.FindAction("SprintAction", throwIfNotFound: true);
        m_PC_Map_ReloadAction = m_PC_Map.FindAction("ReloadAction", throwIfNotFound: true);
        m_PC_Map_ShootAction = m_PC_Map.FindAction("ShootAction", throwIfNotFound: true);
        m_PC_Map_AimAction = m_PC_Map.FindAction("AimAction", throwIfNotFound: true);
        m_PC_Map_JumpAction = m_PC_Map.FindAction("JumpAction", throwIfNotFound: true);
        m_PC_Map_CrouchAction = m_PC_Map.FindAction("CrouchAction", throwIfNotFound: true);
        m_PC_Map_ChangeGunMode = m_PC_Map.FindAction("ChangeGunMode", throwIfNotFound: true);
        m_PC_Map_PrimaryGun = m_PC_Map.FindAction("PrimaryGun", throwIfNotFound: true);
        m_PC_Map_SecondaryGun = m_PC_Map.FindAction("SecondaryGun", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PC_Map
    private readonly InputActionMap m_PC_Map;
    private List<IPC_MapActions> m_PC_MapActionsCallbackInterfaces = new List<IPC_MapActions>();
    private readonly InputAction m_PC_Map_Look;
    private readonly InputAction m_PC_Map_Move;
    private readonly InputAction m_PC_Map_SprintAction;
    private readonly InputAction m_PC_Map_ReloadAction;
    private readonly InputAction m_PC_Map_ShootAction;
    private readonly InputAction m_PC_Map_AimAction;
    private readonly InputAction m_PC_Map_JumpAction;
    private readonly InputAction m_PC_Map_CrouchAction;
    private readonly InputAction m_PC_Map_ChangeGunMode;
    private readonly InputAction m_PC_Map_PrimaryGun;
    private readonly InputAction m_PC_Map_SecondaryGun;
    public struct PC_MapActions
    {
        private @InputMaps m_Wrapper;
        public PC_MapActions(@InputMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_PC_Map_Look;
        public InputAction @Move => m_Wrapper.m_PC_Map_Move;
        public InputAction @SprintAction => m_Wrapper.m_PC_Map_SprintAction;
        public InputAction @ReloadAction => m_Wrapper.m_PC_Map_ReloadAction;
        public InputAction @ShootAction => m_Wrapper.m_PC_Map_ShootAction;
        public InputAction @AimAction => m_Wrapper.m_PC_Map_AimAction;
        public InputAction @JumpAction => m_Wrapper.m_PC_Map_JumpAction;
        public InputAction @CrouchAction => m_Wrapper.m_PC_Map_CrouchAction;
        public InputAction @ChangeGunMode => m_Wrapper.m_PC_Map_ChangeGunMode;
        public InputAction @PrimaryGun => m_Wrapper.m_PC_Map_PrimaryGun;
        public InputAction @SecondaryGun => m_Wrapper.m_PC_Map_SecondaryGun;
        public InputActionMap Get() { return m_Wrapper.m_PC_Map; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PC_MapActions set) { return set.Get(); }
        public void AddCallbacks(IPC_MapActions instance)
        {
            if (instance == null || m_Wrapper.m_PC_MapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PC_MapActionsCallbackInterfaces.Add(instance);
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @SprintAction.started += instance.OnSprintAction;
            @SprintAction.performed += instance.OnSprintAction;
            @SprintAction.canceled += instance.OnSprintAction;
            @ReloadAction.started += instance.OnReloadAction;
            @ReloadAction.performed += instance.OnReloadAction;
            @ReloadAction.canceled += instance.OnReloadAction;
            @ShootAction.started += instance.OnShootAction;
            @ShootAction.performed += instance.OnShootAction;
            @ShootAction.canceled += instance.OnShootAction;
            @AimAction.started += instance.OnAimAction;
            @AimAction.performed += instance.OnAimAction;
            @AimAction.canceled += instance.OnAimAction;
            @JumpAction.started += instance.OnJumpAction;
            @JumpAction.performed += instance.OnJumpAction;
            @JumpAction.canceled += instance.OnJumpAction;
            @CrouchAction.started += instance.OnCrouchAction;
            @CrouchAction.performed += instance.OnCrouchAction;
            @CrouchAction.canceled += instance.OnCrouchAction;
            @ChangeGunMode.started += instance.OnChangeGunMode;
            @ChangeGunMode.performed += instance.OnChangeGunMode;
            @ChangeGunMode.canceled += instance.OnChangeGunMode;
            @PrimaryGun.started += instance.OnPrimaryGun;
            @PrimaryGun.performed += instance.OnPrimaryGun;
            @PrimaryGun.canceled += instance.OnPrimaryGun;
            @SecondaryGun.started += instance.OnSecondaryGun;
            @SecondaryGun.performed += instance.OnSecondaryGun;
            @SecondaryGun.canceled += instance.OnSecondaryGun;
        }

        private void UnregisterCallbacks(IPC_MapActions instance)
        {
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @SprintAction.started -= instance.OnSprintAction;
            @SprintAction.performed -= instance.OnSprintAction;
            @SprintAction.canceled -= instance.OnSprintAction;
            @ReloadAction.started -= instance.OnReloadAction;
            @ReloadAction.performed -= instance.OnReloadAction;
            @ReloadAction.canceled -= instance.OnReloadAction;
            @ShootAction.started -= instance.OnShootAction;
            @ShootAction.performed -= instance.OnShootAction;
            @ShootAction.canceled -= instance.OnShootAction;
            @AimAction.started -= instance.OnAimAction;
            @AimAction.performed -= instance.OnAimAction;
            @AimAction.canceled -= instance.OnAimAction;
            @JumpAction.started -= instance.OnJumpAction;
            @JumpAction.performed -= instance.OnJumpAction;
            @JumpAction.canceled -= instance.OnJumpAction;
            @CrouchAction.started -= instance.OnCrouchAction;
            @CrouchAction.performed -= instance.OnCrouchAction;
            @CrouchAction.canceled -= instance.OnCrouchAction;
            @ChangeGunMode.started -= instance.OnChangeGunMode;
            @ChangeGunMode.performed -= instance.OnChangeGunMode;
            @ChangeGunMode.canceled -= instance.OnChangeGunMode;
            @PrimaryGun.started -= instance.OnPrimaryGun;
            @PrimaryGun.performed -= instance.OnPrimaryGun;
            @PrimaryGun.canceled -= instance.OnPrimaryGun;
            @SecondaryGun.started -= instance.OnSecondaryGun;
            @SecondaryGun.performed -= instance.OnSecondaryGun;
            @SecondaryGun.canceled -= instance.OnSecondaryGun;
        }

        public void RemoveCallbacks(IPC_MapActions instance)
        {
            if (m_Wrapper.m_PC_MapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPC_MapActions instance)
        {
            foreach (var item in m_Wrapper.m_PC_MapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PC_MapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PC_MapActions @PC_Map => new PC_MapActions(this);
    public interface IPC_MapActions
    {
        void OnLook(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnSprintAction(InputAction.CallbackContext context);
        void OnReloadAction(InputAction.CallbackContext context);
        void OnShootAction(InputAction.CallbackContext context);
        void OnAimAction(InputAction.CallbackContext context);
        void OnJumpAction(InputAction.CallbackContext context);
        void OnCrouchAction(InputAction.CallbackContext context);
        void OnChangeGunMode(InputAction.CallbackContext context);
        void OnPrimaryGun(InputAction.CallbackContext context);
        void OnSecondaryGun(InputAction.CallbackContext context);
    }
}
